### ISSUE TITLE
Transfer crate ownership?

### ISSUE THREAD

**Issue by virtualritz** [fulara/ta-lib#1]
Hello Aleksander.

A am maintaining a high level wrapper for TA-Lib and would like to use the `ta-lib` crate name for this. It depends on `ta-lib-sys` which is a low level, `bindgen` autogenerated wrapper around the lib which includes the C code and built-from-source functionality (no binaries shipped).

See here: https://github.com/virtualritz/ta-lib-rs

Thanks is advance for your consideration.

**Comment by fulara** [comment]
Hello @virtualritz 

Yes, let's do this. 
Hm, do you have a link to a procedure?

What should I do?

**Comment by virtualritz** [comment]
I never did this myself. But try:
```
cargo owner --add virtualritz
cargo owner --remove <youralias>
```

**Comment by fulara** [comment]
I have sent you an invite @virtualritz, once you accept I'll remove myself.

**Comment by virtualritz** [comment]
Accepted. Worked. Thank you so much!

**Comment by fulara** [comment]
Okay I have removed myself. good luck @virtualritz
